<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SubInterestsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        try {
            DB::table('sub_interests')->truncate();
            DB::beginTransaction();
            $data = [
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Abs',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Bands',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Body Weight Strength',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Kettlebells',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Weights (Machine)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 1,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Arc Trainer',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Dance',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Elliptical',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Rowing Machine',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Ski Machine',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Stair Mill',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Stair Stepper',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Stationary Bike (recumbent)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Stationary Bike (upright)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Treadmill',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Vertical Climber',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 2,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Anusara',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Ashtanga',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Bikram',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Hatha',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Vinyasa',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 3,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Aerobics',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Aqua Aerobics',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Barre',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Boxing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Circuit Training',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Cross Fit',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'HIIT Training',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                  [
                    'interest_id' => 4,
                    'sub_interest_name' => 'F45 Training',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Jazzercise',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Military Bootcamp',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Pilates',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'P90X',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Spinning',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Step',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'TRX',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Yoga',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Yoga (hot)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Zumba',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 4,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Baseball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Basketball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Boxing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Bowling',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Canoeing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Cycling (Road)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Cycling (Mountain)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                  [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Dance',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Football',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Frisbee',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Gardening',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Golf',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Gymnastics',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Handball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Hiking',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Hockey',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Horseback Riding',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'House Cleaning',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Ice Skating',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Lacrosse',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Martial Arts',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Paddle Ball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Pickle Ball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Rock Climbing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Roller skate/blade',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Rowing (Outdoor)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                  [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Rugby',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (Sprints)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (1 mile)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (5k)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (10k)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (1/2 Marathon)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Running (Marathon)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Sailing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Shoveling (snow)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Skateboarding',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Skiing (cross country)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Skiing (downhill)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Skiing (water)',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Soccer',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Softball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Snow Shoeing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Surfing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Swimming',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Tennis',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Trampoline',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Volleyball',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 5,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => '24 Hour Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Alo',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Anytime Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Apple Fitness +',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Blink Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Burn Boot Camp',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Club Pilates',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                  [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Crunch Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Curves International',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'CycleBar',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Equinox Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'FitBit',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Fitness First',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Fit Body Boot Camp',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Gold’s Gym',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Hard Candy Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Hydrow',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'IFit',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'ILoveKickBoxing',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'LA Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Les Miles',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Map My Run',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Mirror',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Nike Run Club',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Nike Training Club',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Orange Theory',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                  [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Peloton',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Planet Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Pure Barre',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'PURE Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Retro Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Row House',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Runtastic',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Snap Fitness',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Soul Cycle',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Spectrum Athletic Club',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'SPENGA',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Strava',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Sworkit',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'The Alaska Club',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'The Barre Code',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Town Sports International',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'TRX',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'World Gym',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'YogaSix',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Yoga Glow',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'YouFit',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],
                 [
                    'interest_id' => 6,
                    'sub_interest_name' => 'Other',
                    'status' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                 ],

            ];
            DB::table('sub_interests')->insert($data);
            DB::commit();
        } catch (Exception $e) {
            Log::error('Error to run seeder -> '.$e->getMessage());
        }
    }
}
