<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try {
            //DB::table('users')->truncate();
            DB::beginTransaction();
            $data = [
                [
                    'role' => 1,
                    'name' => 'Ron Eliot',
                    'user_name' => 'SIXPAC',
                    'email' => 'ron@sixpac.com',
                    'phone' => '1111111111',
                    'date_of_birth' => '1990-04-14',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 2,
                    'name' => 'Jason Admin',
                    'user_name' => 'jasonadmin',
                    'email' => 'jasonadmin@sixpac.com',
                    'phone' => '2222222222',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 3,
                    'name' => 'Jason Ground',
                    'user_name' => 'jasonground',
                    'email' => 'jason@sixpac.com',
                    'phone' => '3333333333',
                    'date_of_birth' => '1988-10-15',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 4,
                    'name' => 'Employee',
                    'user_name' => 'sixpac_employee',
                    'email' => 'employee@sixpac.com',
                    'phone' => '4444444444',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Consumer',
                    'user_name' => 'sixpac_consumer',
                    'email' => 'consumer@sixpac.com',
                    'phone' => '5555555510',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'KeeerKat',
                    'username' => 'keeerkat',
                    'email' => 'keeerkat@sixpac.com',
                    'phone' => '5555555551',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Ben Dover',
                    'username' => 'bendover',
                    'email' => 'ben@sixpac.com',
                    'phone' => '5555555552',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Addie Minstra',
                    'username' => 'addieminstra',
                    'email' => 'addie@sixpac.com',
                    'phone' => '5555555553',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Hugh Mannerizorsa',
                    'username' => 'hughmannerizorsa',
                    'email' => 'hugh@sixpac.com',
                    'phone' => '5555555554',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Mark Ateer',
                    'username' => 'markateer',
                    'email' => 'markateer@sixpac.com',
                    'phone' => '5555555511',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 0,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Don Messwidme',
                    'username' => 'donmesswidme',
                    'email' => 'donmesswidme@sixpac.com',
                    'phone' => '5555555556',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Annie Versaree',
                    'username' => 'annieversaree',
                    'email' => 'annieversaree@sixpac.com',
                    'phone' => '5555555557',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Ivan Notheridiya',
                    'username' => 'ivannotheridiya',
                    'email' => 'ivan@sixpac.com',
                    'phone' => '5555555558',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 0,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ],
                [
                    'role' => 5,
                    'name' => 'Wiley Waites',
                    'username' => 'wileywaites',
                    'email' => 'wiley@sixpac.com',
                    'phone' => '5555555559',
                    'date_of_birth' => '1987-04-01',
                    'password' => bcrypt('Qwerty@123'),
                    'avtar'=> '',
                    'status' => 1,
                    'social_flag' => 0,
                    'created_by' => 0,
                    'updated_by' => 0,
                    'email_verified_at'=>Carbon::now(),
                    'created_at'=>Carbon::now(),
                    'updated_at'=>Carbon::now(),
                ]

            ];
            DB::table('users')->insert($data);
            DB::commit();
        } catch (Exception $e) {
            Log::error('Error to run seeder -> '.$e->getMessage());
        }
    }
}